### ISSUE TITLE
Copy / paste typo in code snippet at Highlights > Error/Warning Underline > Warning underline

### ISSUE THREAD

**Issue by yannic-bruegger** [CONNECT-platform/codedoc-docs#5]
At https://codedoc.cc/docs/code/highlights#code9-l3

The code snippet for /*~*/ and /*~warning~*/ is identical but should be different. 

```
  new Dictionary<int, int>()./*~*/TryGetValue/*~*/(0);
```
should be
```
  new Dictionary<int, int>()./*~warning~*/TryGetValue/*~warning~*/(0);
```

**Comment by yannic-bruegger** [comment]
Is there a way to collaborate on the codedoc-docs? I'm new here ..
I have fixed the typo and got a fixed branch in my local repo.

**Comment by loreanvictor** [comment]
@yannic-bruegger yes of course! it would be lovely if you could make a pull request.

**Comment by yannic-bruegger** [comment]
Sure! I'll do so tomorrow :) Thanks!

**Comment by loreanvictor** [comment]
corresponding pull request merged, @yannic-bruegger thanks a lot!

**Comment by yannic-bruegger** [comment]
My first pull request on someone else's repo ever - thank you! 😍
