### ISSUE TITLE
Typo in warning box at Highlights > Error/Warning Underline

### ISSUE THREAD

**Issue by yannic-bruegger** [CONNECT-platform/codedoc-docs#6]
At https://codedoc.cc/docs/code/highlights#errorwarning-underline

> Since /*~*/ and /*~warn*/ are interleaved within rest of the syntax, they ONLY WORK in languages supporting /* ... */ comment syntax. They are also not pre-processed, so they will be copied alongside the rest of the code.

should be

> Since /*~*/ and /*~warn~*/ are interleaved within rest of the syntax, they ONLY WORK in languages supporting /* ... */ comment syntax. They are also not pre-processed, so they will be copied alongside the rest of the code.

**Comment by loreanvictor** [comment]
@yannic-bruegger thanks for the heads up, could you also make a pull request for this?

**Comment by loreanvictor** [comment]
pull request merged, @yannic-bruegger thanks a lot!
